[package]
name = "evil-id"
version = "0.1.0"
edition = "2024"

[features]
serde = ["dep:serde"]
beep = []
all = ["serde", "beep"]

[dependencies]
serde = { optional = true, version = "1.0.219" }
rand = "0.9.2"
